<?php

/**
 * @file
 * Contains ss_invoice.module.
 */

/**
 * Implements hook_theme().
 */
function ss_invoice_theme()
{
  return [
    'invoice_template' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'invoice_index' => [
      'variables' => [
        'data' => NULL,
      ],
    ],

    'delivery_slip_index' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'delivery_slip_template' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'sales_chart_block' => [
      'variables' => [
        'sales_data' => NULL,
        'labels' => NULL,
        'total_sales' => NULL,
      ],
      'template' => 'sales-chart-block',
    ],
    'total_orders_block' => [
      'variables' => [
        'orders_data' => NULL,
        'labels' => NULL,
        'percentage_increase' => NULL,
      ],
      'template' => 'total-orders-block',
    ],
    'total_users_chart' => [
      'variables' => [
        'users_data' => NULL,
        'labels' => NULL,
        'percentage_increase' => NULL,
      ],
      'template' => 'total-users-chart',
    ],

  ];
}
