<?php

/**
 * @file
 * Contains ss_invoice.module.
 */

/**
 * Implements hook_theme().
 */
function ss_invoice_theme() {
  return [
    'invoice_template' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'invoice_index' => [
      'variables' => [
        'data' => NULL,
      ],
    ],

    'delivery_slip_index' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'delivery_slip_template' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
}
