<?php

/**
 * @file
 * Contains ss_dashboard.module.
 */

/**
 * Implements hook_theme().
 */
function ss_dashboard_theme() {
  return [
    'sales_chart_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'sales-chart-block',
    ],
    'total_revenue_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'total-revenue-block',
    ],
    'total_orders_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'total-orders-block',
    ],
    'total_users_chart' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'total-users-chart',
    ],
    'earnings_widget_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'earnings-widget-block',
    ],
  ];
}
