<?php

/**
 * @file
 * Contains commerce_ai_intelligence.module.
 */

/**
 * Implements hook_theme().
 */
function commerce_ai_intelligence_theme() {
  return [
    // Market Insights.
    'ai_intelligence_insights_controller' => [
      'variables' => ['data' => NULL],
      'template' => 'ai_intelligence/insights/insights-controller',
    ],
    'ai_intelligence_insight_detail' => [
      'variables' => ['data' => NULL],
      'template' => 'ai_intelligence/insights/insight-detail',
    ],
    'ai_intelligence_insight_product_modal' => [
      'variables' => ['product' => NULL],
      'template' => 'ai_intelligence/insights/insight-product-modal',
    ],

    // Forecast.
    'ai_intelligence_forecast_controller' => [
      'variables' => ['data' => NULL],
      'template' => 'ai_intelligence/forecast/forecast-controller',
    ],
    'ai_intelligence_forecast_detail' => [
      'variables' => ['data' => NULL],
      'template' => 'ai_intelligence/forecast/forecast-detail',
    ],
    'ai_intelligence_forecast_product_modal' => [
      'variables' => ['product' => NULL],
      'template' => 'ai_intelligence/forecast/forecast-product-modal',
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function commerce_ai_intelligence_preprocess_html(array &$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  if (str_starts_with($route_name, 'commerce_ai_intelligence.')) {
    $variables['attributes']['class'][] = 'commerce-ai-intelligence-page';
    $variables['#attached']['library'][] = 'commerce_ai_intelligence/commerce_ai_intelligence.ai_intelligence';
  }
}
